### ISSUE TITLE
Namespace permissions

### ISSUE THREAD

**Issue by Grinnz** [sciurius/perl-String-Interpolate-Named#1]
The permissions for this module namespace are currently held by ILTZU as seen here: https://cpanmeta.grinnz.com/perms#=Text::Substitute

However, they have not made a CPAN release since 2001 and I cannot find a record of them releasing this module. I would suggest emailing them at their [configured email](https://cpanmeta.grinnz.com/authors#=iltzu) and CC `modules@perl.org` requesting that the namespace be released for your use in PAUSE.

**Comment by sciurius** [comment]
Renamed to String::Interpolate::Named.
